-- Extend kb_entries with additional attributes used by the UI
-- Safe to run multiple times via IF NOT EXISTS checks

alter table if exists kb_entries
  add column if not exists section_id text,
  add column if not exists status text,
  add column if not exists effective_date date,
  add column if not exists amendment_date date,
  add column if not exists last_reviewed date,
  add column if not exists visibility jsonb default '{"gli": true, "cpa": false}'::jsonb,
  add column if not exists source_urls jsonb default '[]'::jsonb,
  add column if not exists elements jsonb default '[]'::jsonb,
  add column if not exists penalties jsonb default '[]'::jsonb,
  add column if not exists defenses jsonb default '[]'::jsonb,
  add column if not exists prescriptive_period text,
  add column if not exists standard_of_proof text,
  add column if not exists rule_no text,
  add column if not exists section_no text,
  add column if not exists triggers jsonb default '[]'::jsonb,
  add column if not exists time_limits jsonb default '[]'::jsonb,
  add column if not exists required_forms jsonb default '[]'::jsonb,
  add column if not exists circular_no text,
  add column if not exists applicability jsonb default '[]'::jsonb,
  add column if not exists issuance_no text,
  add column if not exists instrument_no text,
  add column if not exists supersedes jsonb default '[]'::jsonb,
  add column if not exists steps_brief jsonb default '[]'::jsonb,
  add column if not exists forms_required jsonb default '[]'::jsonb,
  add column if not exists failure_states jsonb default '[]'::jsonb,
  add column if not exists violation_code text,
  add column if not exists violation_name text,
  add column if not exists license_action text,
  add column if not exists fine_schedule jsonb default '[]'::jsonb,
  add column if not exists apprehension_flow jsonb default '[]'::jsonb,
  add column if not exists incident text,
  add column if not exists phases jsonb default '[]'::jsonb,
  add column if not exists forms jsonb default '[]'::jsonb,
  add column if not exists handoff jsonb default '[]'::jsonb,
  add column if not exists rights_callouts jsonb default '[]'::jsonb,
  add column if not exists rights_scope text,
  add column if not exists advice_points jsonb default '[]'::jsonb,
  add column if not exists topics jsonb default '[]'::jsonb,
  add column if not exists jurisprudence jsonb default '[]'::jsonb,
  add column if not exists legal_bases jsonb default '[]'::jsonb,
  add column if not exists related_sections jsonb default '[]'::jsonb;


