import React, { useState } from 'react';
import { Button } from './ui/Button';
import { Textarea } from './ui/Textarea';
import Modal from './Modal/Modal';

interface ImportJsonModalProps {
  isOpen: boolean;
  onClose: () => void;
  onImport: (jsonText: string) => void;
}

export function ImportJsonModal({ isOpen, onClose, onImport }: ImportJsonModalProps) {
  const [jsonText, setJsonText] = useState('');
  const [error, setError] = useState('');

  const handleImport = () => {
    if (!jsonText.trim()) {
      setError('Please enter JSON text');
      return;
    }

    try {
      // Validate JSON format
      JSON.parse(jsonText);
      setError('');
      onImport(jsonText);
    } catch (err) {
      setError('Invalid JSON format. Please check your input.');
    }
  };

  const handleClose = () => {
    setJsonText('');
    setError('');
    onClose();
  };

  return (
    <Modal 
      isOpen={isOpen} 
      onClose={handleClose}
      title="Import Entry from JSON"
      subtitle="Paste the JSON text generated by GPT or any other source to prefill the entry form."
    >
      <div className="p-6 max-w-2xl w-full">
        <div className="mb-4">
          <label htmlFor="json-input" className="block text-sm font-medium text-gray-700 mb-2">
            JSON Text
          </label>
          <Textarea
            id="json-input"
            value={jsonText}
            onChange={(e) => setJsonText(e.target.value)}
            placeholder="Paste your JSON entry here..."
            className="min-h-[300px] font-mono text-sm"
            rows={12}
          />
          {error && (
            <p className="text-red-600 text-sm mt-2">{error}</p>
          )}
        </div>

        <div className="flex justify-end gap-3">
          <Button
            type="button"
            variant="outline"
            onClick={handleClose}
          >
            Go Back
          </Button>
          <Button
            type="button"
            onClick={handleImport}
            disabled={!jsonText.trim()}
          >
            Import Entry
          </Button>
        </div>
      </div>
    </Modal>
  );
}
