import React, { useState } from 'react';
import { Button } from './ui/Button';
import { Textarea } from './ui/Textarea';
import Modal from './Modal/Modal';

interface ImportJsonModalProps {
  isOpen: boolean;
  onClose: () => void;
  onImport: (jsonText: string) => void;
}

export function ImportJsonModal({ isOpen, onClose, onImport }: ImportJsonModalProps) {
  const [jsonText, setJsonText] = useState('');
  const [error, setError] = useState('');

  const handleImport = () => {
    if (!jsonText.trim()) {
      setError('Please enter JSON text');
      return;
    }

    try {
      // Validate JSON format
      JSON.parse(jsonText);
      setError('');
      onImport(jsonText);
    } catch (err) {
      setError('Invalid JSON format. Please check your input.');
    }
  };

  const handleClose = () => {
    setJsonText('');
    setError('');
    onClose();
  };

  return (
    <Modal 
      isOpen={isOpen} 
      onClose={handleClose}
      title="Import Entry from JSON"
      subtitle="Paste the JSON text generated by GPT or any other source to prefill the entry form."
    >
      <div className="max-w-4xl w-full mx-auto">
        <div className="space-y-6">
          {/* JSON Input Section */}
          <div className="space-y-3">
            <label htmlFor="json-input" className="block text-sm font-semibold text-gray-900">
              JSON Text
            </label>
            <div className="relative">
              <Textarea
                id="json-input"
                value={jsonText}
                onChange={(e) => setJsonText(e.target.value)}
                placeholder="Paste your JSON entry here..."
                className="min-h-[400px] font-mono text-sm border-2 border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 rounded-lg resize-none"
                rows={16}
              />
              {jsonText && (
                <div className="absolute top-2 right-2 bg-gray-100 text-gray-600 text-xs px-2 py-1 rounded">
                  {jsonText.length} characters
                </div>
              )}
            </div>
            {error && (
              <div className="flex items-center space-x-2 text-red-600 text-sm">
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                </svg>
                <span>{error}</span>
              </div>
            )}
          </div>

          {/* Help Text */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <div className="flex items-start space-x-3">
              <svg className="w-5 h-5 text-blue-600 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
              </svg>
              <div className="text-sm text-blue-800">
                <p className="font-medium mb-1">Tips for successful import:</p>
                <ul className="list-disc list-inside space-y-1 text-blue-700">
                  <li>Ensure your JSON is properly formatted with valid syntax</li>
                  <li>Include all required fields like <code className="bg-blue-100 px-1 rounded">entry_id</code>, <code className="bg-blue-100 px-1 rounded">title</code>, and <code className="bg-blue-100 px-1 rounded">type</code></li>
                  <li>Copy the entire JSON object from your source</li>
                </ul>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex justify-between items-center pt-4 border-t border-gray-200">
            <div className="text-sm text-gray-500">
              {jsonText.trim() ? 'Ready to import' : 'Enter JSON text to continue'}
            </div>
            <div className="flex space-x-3">
              <Button
                type="button"
                variant="outline"
                onClick={handleClose}
                className="px-6 py-2"
              >
                Go Back
              </Button>
              <Button
                type="button"
                onClick={handleImport}
                disabled={!jsonText.trim()}
                className="px-6 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed"
              >
                Import Entry
              </Button>
            </div>
          </div>
        </div>
      </div>
    </Modal>
  );
}
