import React, { useState } from 'react';
import { Button } from './ui/Button';
// Bypass UI Textarea to fully control theme styling for this modal
import Modal from './Modal/Modal';

interface ImportJsonModalProps {
  isOpen: boolean;
  onClose: () => void;
  onImport: (jsonText: string) => void;
}

export function ImportJsonModal({ isOpen, onClose, onImport }: ImportJsonModalProps) {
  const [jsonText, setJsonText] = useState('');
  const [error, setError] = useState('');
  const isDark = (typeof document !== 'undefined') && (
    document.documentElement.classList.contains('dark-mode') ||
    document.body.classList.contains('dark-mode')
  );
  const textareaStyle: React.CSSProperties = {
    height: 'calc(100% - 16px)',
    width: '100%',
    backgroundColor: isDark ? '#1f2937' : '#f3f4f6',
    color: isDark ? '#e5e7eb' : '#111827'
  };

  const handleImport = () => {
    if (!jsonText.trim()) {
      setError('Please enter JSON text');
      return;
    }

    try {
      // Validate JSON format
      JSON.parse(jsonText);
      setError('');
      onImport(jsonText);
    } catch (err) {
      setError('Invalid JSON format. Please check your input.');
    }
  };

  const handleClose = () => {
    setJsonText('');
    setError('');
    onClose();
  };

  return (
    <Modal 
      isOpen={isOpen} 
      onClose={handleClose}
      title="Import Entry from JSON"
      subtitle="Paste the JSON text generated by GPT or any other source to prefill the entry form."
    >
      <div className="max-w-4xl w-full mx-auto h-[70vh] flex flex-col">
        <div className="flex-1 flex flex-col space-y-4">
          {/* JSON Input Section */}
          <div className="flex-1 flex flex-col">
            <div className="relative flex-1">
              <textarea
                id="json-input"
                value={jsonText}
                onChange={(e) => setJsonText(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    handleImport();
                  }
                }}
                placeholder="Paste your JSON entry here..."
                className="json-textarea w-full h-full font-mono text-sm border-2 !border-gray-200 focus:!border-blue-500 focus:!ring-2 focus:!ring-blue-200 rounded-lg resize-none placeholder:pl-4 placeholder:pt-3"
                style={textareaStyle}
                rows={16}
              />
              {jsonText && (
                <div className="absolute top-2 right-8 bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 text-xs px-2 py-1 rounded">
                  {jsonText.length} characters
                </div>
              )}
            </div>
            {error && (
              <div className="flex items-center space-x-2 text-red-600 text-sm">
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                </svg>
                <span>{error}</span>
              </div>
            )}
          </div>

          {/* Action Buttons */}
          <div className="mt-auto flex justify-end items-center pt-8">
            <div className="flex gap-3">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleClose}
                className="!px-4 !py-2 text-sm font-medium"
                style={{ padding: '8px 16px' }}
              >
                Go Back
              </Button>
              <Button
                type="button"
                size="sm"
                onClick={handleImport}
                disabled={!jsonText.trim()}
                className="!px-4 !py-2 text-sm font-medium bg-green-600 hover:bg-green-700 disabled:bg-gray-300 disabled:cursor-not-allowed text-white"
                style={{ padding: '8px 16px' }}
              >
                Import Entry
              </Button>
            </div>
          </div>
        </div>
      </div>
    </Modal>
  );
}
